package com.example.iboto;

import java.util.ArrayList;

public class ListDetails {
    public static ArrayList<Model> getPresLists(){
        ArrayList<Model> candidateLists = new ArrayList<>();

        candidateLists.add(new Model(R.drawable.abella_ernie, "1. Abella, Ernie","Independent", "Ernie Abella, 72, is a businessman, writer, and pastor who is a long-time supporter of President Rodrigo Duterte. He also briefly served as the president’s spokesperson.", "Good Governance,Access to Services","Writer, Formed a cooperative and a secondary school, Headed private businesses,Founder of the Hope of Asia and Jesus Fellowship, Inc, a charismatic group" ));

        candidateLists.add(new Model(R.drawable.leody, "2. De Guzman, Leody","Partido Lakas ng Masa", "Leody de Guzman, 61, is an activist and labor leader who has pushed for policies to secure the rights and welfare of workers since 1984. He ran for senator in 2019 under the tagline \"Manggagawa Naman\" but failed to secure a seat. He currently sits as chairperson of the Bukluran ng Manggagawang Pilipino, a socialist labor center and federation of militant trade unions.", "Health and Pandemic Response, Workers Right and Welfare, Climate, Security, Economic and income Inequality","De Guzman has served as chairman of the Bukluran ng Manggagawang Pilipino since 2018 but has been a ranking member of the socialist labor center since its inception in 1993. " ));
        candidateLists.add(new Model(R.drawable.isko, "3. Domagoso, Isko Moreno","Aksyon Demokratiko", "Francisco \"Isko Moreno\" Domagoso is the incumbent mayor of the City of Manila. After serving as the capital city's vice mayor from 2007 to 2016, he ran for senator but failed to secure a seat. He was then appointed by President Rodrigo Duterte as chairman of the board of the North Luzon Railways Corporation and later, undersecretary at the Department of Social Welfare and Development.", "Public infrastructure forbasic needs social services and health, COVID-19 response, Vaccine hesitancy, Countryside Development, Education in Far flung areas, Peace and order","Oversees Manila's COVID-19 pandemic response, City “beautification” project, and thrust towards low-cost housing in slum areas,Improvement of health facilities, Support for education, Ayuda such as benefits under Ordinance No. 8565" ));
        candidateLists.add(new Model(R.drawable.noberto, "4. Gonzales, Norberto","PARTIDO DEMOKTRATIKO SOSYALISTA PILIPINAS", "Norberto B. Gonzales, 74, is an avowed democratic-socialist, whose long career spans activism and union organizing, peace talks negotiation and national security adviser, defense secretary and presidential chief of staff appointments under the Gloria Macapagal-Arroyo administration. He chairs the Philip\u00ADpine Democratic Socialist Party, which has roots in the protest movement in the 1970s and participated in the mass campaigns against the Marcos dictatorship, peace talks with the Moro National Liberation Front and the ouster of President Joseph Ejercito Estrada.", "Agriculture, Health, Covid19, Administrative Priorities, National Security","Part of the formulation and execution of Oplan Bantay Laya, Final Peace Agreement between the Philippine government and the MNLF" ));
        candidateLists.add(new Model(R.drawable.ping, "5. Lacson, Ping","PARTIDO PARA SA DEMOKRATIKONG REPORMA", "Ping Lacson, 73, has served in the legislative and executive branches of the government for over 40 years. He is currently serving his third term in the Senate.", "Anti Corruption, Budget Reform, Anti-Insurgency, Economic Recovery, Digitization, Health, Covid 19 Pandemic","R.A No. 11479, or the Anti-Terrorism Act of 2020,R.A. 11469 or the Bayanihan to Heal as One Act of 2020, R.A. No. 8049, or the Anti-Hazing Act of 2018, R.A. No. 1738, or the Philippine Identification System Act of 2018, R.A. 10354 or the Reproductive Health Act of 2011" ));
        candidateLists.add(new Model(R.drawable.faisal, "6. Mangondato, Faisal","KATIPUNAN NG KAMALAYANG KAYUMANGGI", "Faisal Mangondato is a businessman who is running as the standard-bearer of the Katipunan ng Kamalayang Kayumanggi party. He was born in Ramain Ditsaan, Lanao del Sur, and currently resides in Marawi City.", "Improve Political System, Economy, Labor, Crime and Justice, Family;Social Issues, Environment","There is no publicly available information on this matter at this time. Requested information from the candidate was not provided."));
        candidateLists.add(new Model(R.drawable.bbm, "7. Marcos, Ferdinand Jr.","PARTIDO FEDERAL NG PILIPINAS", "Ferdinand “Bongbong” Marcos Jr., 64, son and namesake of the late ousted dictator, was elected unopposed into vice gubernatorial seats in Ilocos Norte at the height of his father’s regime in 1980, and eventually into congressional seats representing the same province after his family’s return to the Philippines in 1991. He also served as a senator from 2010 to 2016 before losing a bid for higher office to Vice President Leni Robredo in the 2016 elections.", "Health and Pandemic Response, Anti-Insurgency, Law and Order, Environment and Climate Change, Disaster Risk and Reduction Management","R.A. No. 108841 or the Balanced Housing Development Program Amendments, R.A. 10821 or the Children’s Emergency Relief and Protection Act, R.A. 10586 or the Anti-Drunk and Drugged Driving Act of 2012, R.A. 10175 of the Cybercrime Prevention Act of 2011" ));
        candidateLists.add(new Model(R.drawable.jose_m, "8. Montemayor, Jose","DEMOCRACTIC PARTY OF THE PHILIPPINES", "Jose Montemayor Jr. works primarily as a cardiologist at major hospitals. He claims to bring a medical, legal and economics background to the presidential race and his first campaign for public office.", "Anti-Crime, Covid-19 Response, Efficient Governance, West Philippine Sea, Sectoral reforms","St. Luke’s Medical Center National Kidney Institute, Philippine Heart Center Consultant in Clinical Cardiology and Interventional Cardiology,Professor of Law and Professor, Graduate (MBA, LLM, Ph.D.) ,Professor of Law and Professor, Graduate Studies (MBA, LLM, Ph.D.)" ));
        candidateLists.add(new Model(R.drawable.pacquiao, "9. Pacquiao, Manny","ABAG PROMDI", "Manny Pacquiao is a Philippine legislator who has served in both chambers of Congress since 2010. He first gained acclaim as a world-class champion boxer and juggled his careers as a public official and athlete until 2021 when he announced his retirement from the sport. The boxer-turned-legislator is also a preacher and founded the church Word for Everyone Ministries International, Inc. in 2012.", "Covid19-Pandemic response, Anti corruption","Founded Word for Everyone Ministries International, Inc., a church, in General Santos City (2012), R.A. 11592 or the LPG Industry Regulation Act,R.A. 11469 or the Bayanihan to Heal As One Act, RA No. 11163 or the National Bible Day Act, R.A. No. 11227 or the Handbook for OFWs Act of 2018, R.A. 11201 or the Department of Human Settlements and Urban Development Act" ));

        candidateLists.add(new Model(R.drawable.robredo, "10. Robredo, Leni","Independent", "Leni Robredo, 56, is currently serving as the 14th vice president of the Philippines. Her office has garnered the highest audit rating from the Commission on Audit for three consecutive years (2018-2020) and has been recognized by Malacañang for its pandemic response programs across the country.Her flagship program as vice president, Angat Buhay, is an anti-poverty program providing and coordinating support through multiple advocacy areas, namely food security and nutrition, healthcare, public education, rural development, housing, and resettlement and women empowerment. The Angat Buhay Program has mobilized at least P520 million worth of resources for the benefit of 321,000 families and 223 communities nationwide, according to the latest updates as of this writing.", "Restore Trust In Government, Boost Strength of Philippine Industry, End Workplace Discrimination, Support Small Business, Support the Unemployed","Republic Act (R.A.) No. 10708, or the Tax Incentives Management and Transparency Act, R.A. 10922 or the Economic and Financial Literacy Act, Angat Buhay Program, an anti-poverty program involving multiple advocacy areas, COVID-19 Response, multi-sectoral pandemic relief programs, Improvement of the OVP, Relief Operations" ));

        return candidateLists;
    }
}
