package com.example.iboto;

import java.util.ArrayList;

public class ListDetails {
    public static ArrayList<Model> getPresLists(){
        ArrayList<Model> candidateLists = new ArrayList<>();

        candidateLists.add(new Model(R.drawable.abella_ernie, "1. Abella, Ernie","Independent", "Ernie Abella, 72, is a businessman, writer, and pastor who is a long-time supporter of President Rodrigo Duterte. He also briefly served as the president’s spokesperson.", "Good Governance,Access to Services","Writer, Formed a cooperative and a secondary school, Headed private businesses,Founder of the Hope of Asia and Jesus Fellowship, Inc, a charismatic group" ));

        candidateLists.add(new Model(R.drawable.leody, "2. De Guzman, Leody","Partido Lakas ng Masa", "Leody de Guzman, 61, is an activist and labor leader who has pushed for policies to secure the rights and welfare of workers since 1984. He ran for senator in 2019 under the tagline \"Manggagawa Naman\" but failed to secure a seat. He currently sits as chairperson of the Bukluran ng Manggagawang Pilipino, a socialist labor center and federation of militant trade unions.", "Health and Pandemic Response, Workers Right and Welfare, Climate, Security, Economic and income Inequality","De Guzman has served as chairman of the Bukluran ng Manggagawang Pilipino since 2018 but has been a ranking member of the socialist labor center since its inception in 1993. " ));
        candidateLists.add(new Model(R.drawable.isko, "3. Domagoso, Isko Moreno","Aksyon Demokratiko", "Francisco \"Isko Moreno\" Domagoso is the incumbent mayor of the City of Manila. After serving as the capital city's vice mayor from 2007 to 2016, he ran for senator but failed to secure a seat. He was then appointed by President Rodrigo Duterte as chairman of the board of the North Luzon Railways Corporation and later, undersecretary at the Department of Social Welfare and Development.", "Public infrastructure forbasic needs social services and health, COVID-19 response, Vaccine hesitancy, Countryside Development, Education in Far flung areas, Peace and order","Oversees Manila's COVID-19 pandemic response, City “beautification” project, and thrust towards low-cost housing in slum areas,Improvement of health facilities, Support for education, Ayuda such as benefits under Ordinance No. 8565" ));
        candidateLists.add(new Model(R.drawable.noberto, "4. Gonzales, Norberto","PARTIDO DEMOKTRATIKO SOSYALISTA PILIPINAS", "Norberto B. Gonzales, 74, is an avowed democratic-socialist, whose long career spans activism and union organizing, peace talks negotiation and national security adviser, defense secretary and presidential chief of staff appointments under the Gloria Macapagal-Arroyo administration. He chairs the Philip\u00ADpine Democratic Socialist Party, which has roots in the protest movement in the 1970s and participated in the mass campaigns against the Marcos dictatorship, peace talks with the Moro National Liberation Front and the ouster of President Joseph Ejercito Estrada.", "Agriculture, Health, Covid19, Administrative Priorities, National Security","Part of the formulation and execution of Oplan Bantay Laya, Final Peace Agreement between the Philippine government and the MNLF" ));
        candidateLists.add(new Model(R.drawable.ping, "5. Lacson, Ping","PARTIDO PARA SA DEMOKRATIKONG REPORMA", "Ping Lacson, 73, has served in the legislative and executive branches of the government for over 40 years. He is currently serving his third term in the Senate.", "Anti Corruption, Budget Reform, Anti-Insurgency, Economic Recovery, Digitization, Health, Covid 19 Pandemic","R.A No. 11479, or the Anti-Terrorism Act of 2020,R.A. 11469 or the Bayanihan to Heal as One Act of 2020, R.A. No. 8049, or the Anti-Hazing Act of 2018, R.A. No. 1738, or the Philippine Identification System Act of 2018, R.A. 10354 or the Reproductive Health Act of 2011" ));
        candidateLists.add(new Model(R.drawable.faisal, "6. Mangondato, Faisal","KATIPUNAN NG KAMALAYANG KAYUMANGGI", "Faisal Mangondato is a businessman who is running as the standard-bearer of the Katipunan ng Kamalayang Kayumanggi party. He was born in Ramain Ditsaan, Lanao del Sur, and currently resides in Marawi City.", "Improve Political System, Economy, Labor, Crime and Justice, Family;Social Issues, Environment","There is no publicly available information on this matter at this time. Requested information from the candidate was not provided."));
        candidateLists.add(new Model(R.drawable.bbm, "7. Marcos, Ferdinand Jr.","PARTIDO FEDERAL NG PILIPINAS", "Ferdinand “Bongbong” Marcos Jr., 64, son and namesake of the late ousted dictator, was elected unopposed into vice gubernatorial seats in Ilocos Norte at the height of his father’s regime in 1980, and eventually into congressional seats representing the same province after his family’s return to the Philippines in 1991. He also served as a senator from 2010 to 2016 before losing a bid for higher office to Vice President Leni Robredo in the 2016 elections.", "Health and Pandemic Response, Anti-Insurgency, Law and Order, Environment and Climate Change, Disaster Risk and Reduction Management","R.A. No. 108841 or the Balanced Housing Development Program Amendments, R.A. 10821 or the Children’s Emergency Relief and Protection Act, R.A. 10586 or the Anti-Drunk and Drugged Driving Act of 2012, R.A. 10175 of the Cybercrime Prevention Act of 2011" ));
        candidateLists.add(new Model(R.drawable.jose_m, "8. Montemayor, Jose","DEMOCRACTIC PARTY OF THE PHILIPPINES", "Jose Montemayor Jr. works primarily as a cardiologist at major hospitals. He claims to bring a medical, legal and economics background to the presidential race and his first campaign for public office.", "Anti-Crime, Covid-19 Response, Efficient Governance, West Philippine Sea, Sectoral reforms","St. Luke’s Medical Center National Kidney Institute, Philippine Heart Center Consultant in Clinical Cardiology and Interventional Cardiology,Professor of Law and Professor, Graduate (MBA, LLM, Ph.D.) ,Professor of Law and Professor, Graduate Studies (MBA, LLM, Ph.D.)" ));
        candidateLists.add(new Model(R.drawable.pacquiao, "9. Pacquiao, Manny","ABAG PROMDI", "Manny Pacquiao is a Philippine legislator who has served in both chambers of Congress since 2010. He first gained acclaim as a world-class champion boxer and juggled his careers as a public official and athlete until 2021 when he announced his retirement from the sport. The boxer-turned-legislator is also a preacher and founded the church Word for Everyone Ministries International, Inc. in 2012.", "Covid19-Pandemic response, Anti corruption","Founded Word for Everyone Ministries International, Inc., a church, in General Santos City (2012), R.A. 11592 or the LPG Industry Regulation Act,R.A. 11469 or the Bayanihan to Heal As One Act, RA No. 11163 or the National Bible Day Act, R.A. No. 11227 or the Handbook for OFWs Act of 2018, R.A. 11201 or the Department of Human Settlements and Urban Development Act" ));

        candidateLists.add(new Model(R.drawable.robredo, "10. Robredo, Leni","Independent", "Leni Robredo, 56, is currently serving as the 14th vice president of the Philippines. Her office has garnered the highest audit rating from the Commission on Audit for three consecutive years (2018-2020) and has been recognized by Malacañang for its pandemic response programs across the country.Her flagship program as vice president, Angat Buhay, is an anti-poverty program providing and coordinating support through multiple advocacy areas, namely food security and nutrition, healthcare, public education, rural development, housing, and resettlement and women empowerment. The Angat Buhay Program has mobilized at least P520 million worth of resources for the benefit of 321,000 families and 223 communities nationwide, according to the latest updates as of this writing.", "Restore Trust In Government, Boost Strength of Philippine Industry, End Workplace Discrimination, Support Small Business, Support the Unemployed","Republic Act (R.A.) No. 10708, or the Tax Incentives Management and Transparency Act, R.A. 10922 or the Economic and Financial Literacy Act, Angat Buhay Program, an anti-poverty program involving multiple advocacy areas, COVID-19 Response, multi-sectoral pandemic relief programs, Improvement of the OVP, Relief Operations" ));

        return candidateLists;
    }

    public static ArrayList<Model> getVPLists(){
        ArrayList<Model> candidateLists = new ArrayList<>();

        candidateLists.add(new Model(R.drawable.atienza, "1. ATIENZA, LITO","ABAG PROMDI", "Lito Atienza, 80, has represented the Buhay party-list as a lawmaker in the lower house since 2012.He has held several seats in the City of Manila since the 1970s, ultimately becoming mayor for three consecutive years from 1998 to 2007. His appointment as Secretary of Environment and Natural Resources under the Arroyo administration from 2007 to 2009 also drew criticism from environmentalists who disapproved of his anti-conservation record as mayor.", "Good Government, Anti Corruption, Anti-Death penalty, Anti Artificial Contraceptives","R.A. 11291 or the Magna Carta of the Poor, R.A. 11207 or An Act Providing for Reasonable Rates for Political Advertisements, R.A. 11363 or the Philippine Space Act,R.A. 11215 or the National Integrated Cancer Control Act,R.A. 11350 or the National Commission of Senior Citizens Act" ));

        candidateLists.add(new Model(R.drawable.bello, "2. BELLO, WALDEN","PARTIDO LAKAS NG MASA", "Walden Bello, 76, has been an activist, social worker, academic and political analyst since the mid-70s. He ran for senator in the 2016 elections as an independent but failed to secure a seat, placing 36th with just 2.41% of the total votes.", "Health and pandemic Response, Workers Rights, Climate, Security, Economy; Income Inequality","R.A. 10368 or the Human Rights Victims Reparation and Recognition Act of 2013, R.A. 10354 or the Responsible Parenthood and Reproductive Health Act of 2012,R.A. 9700 or the Comprehensive Agrarian Reform Program, R.A. 10655 or An Act Repealing the Crime of Premature Marriage under Article 351 of Act No. 3815, or the Revised Penal Code, R.A. 10667 or the Philippine Competition Act,R.A. 10742 or the Sangguniang Kabataan Reform Act of 2015" ));

        candidateLists.add(new Model(R.drawable.david, "3. DAVID, RIZALITO","DEMOCRATIC PARTY OF THE PHILIPPINES", "Rizalito David, 60, is a pro-life advocate and perennial candidate for public office. A near-constant presence in previous elections, he filed two unsuccessful petitions to disqualify Senator Grace Poe and then-Davao City Mayor Rodrigo Duterte from the presidential race in 2016. This was after he was declared a nuisance candidate for the same race.", "Faith revolution, Covid-19 Response, Anti Corruption, Education","In his campaigns for public office, David claimed that his extensive experience in various legislative staffs, background in sociology and environmental studies and experience in the Department of Environment and Natural Resources gave him an edge. According to him, he worked on the Clean Air Act, the Solid Waste Management Act, the Clean Water Act and the Philippine Mining Law." ));

        candidateLists.add(new Model(R.drawable.duterte, "4. DUTERTE, SARA","LAKAS CHRISTIAN MUSLIM DEMOCRATS", "Sara Duterte, 43, is the incumbent mayor of Davao City. She became the city's first female mayor and the youngest to ever be elected in its history. She is the daughter of President Rodrigo Duterte who also served as mayor of the southern city for several terms before seeking the country's highest office.Duterte is the running-mate of Ferdinand \"Bongbong\" Marcos Jr., a former senator who is also the son and namesake of the late ousted dictator. She entered the vice presidential race at the last hour via substitution after initially claiming that she had no interest in seeking a national post.", "Changing System of Government, Health Care System, Mandatory Military Service, Disaster preparedness","Under Duterte's watch, Davao became the eighth richest city in the country in 2020, climbing one spot from the year before. Davao was also ranked the fourth most urbanized city by the Department of Trade and Industry as of 2021, based on the metrics of economic dynamism, government efficiency, infrastructure, and resiliency.She gained national attention after she repeatedly punched a Regional Trial Court sheriff in July 2011 for which she faced administrative and criminal complaints. Duterte was also reprimanded by the Office of the Ombudsman over the matter and faces disbarment complaints. She apologized but said she was ready to “face the consequences.\"" ));

        candidateLists.add(new Model(R.drawable.lopez, "5. LOPEZ, MANNY SD","WORKERS AND PEASANTS PARTY", "Manny SD Lopez is an economist and management professional touting decades of local and international experience. He headed Empowered People’s Initiative and Reform Movement Alliance or ePIRMa, which advocated for people’s initiative as a means of charter change, and the 2.22 Coalition, which sought government reforms and the mass resignation of top officials in favor of a “transition government” during the administration of President Benigno Aquino III.", "Three Pronged Economic Recovery Plan, System Change and Structural Reform, Agricultural Reform, Disaster management, Education Reform","Lopez has focused his efforts in the last decade in advocacy work, primarily pushing for government reforms including charter change through people’s initiative and anti-corruption measures." ));

        candidateLists.add(new Model(R.drawable.ong, "6. ONG, DOC WILLIE","AKSYON DEMOKRATIKO", "Doc Willie Ong, 58, is an internal medicine specialist, cardiologist, author and medical commentator who gained popularity primarily through social media where he offers medical and healthcare-related advice.Ong also briefly served as a Department of Health consultant. He left ABS-CBN’s Salamat Doc in 2018 to run for the Senate, running a campaign backed by his substantial online presence and strong support from migrant Filipino workers. For a neophyte candidate, Ong placed a surprisingly high 18th place in the polls with 7.6 million votes.", "Health, Covid 19- Response","Ong was a consultant with the DOH from 2010 to 2014.Ong worked as an internal medicine specialist and cardiologist while building his mainstream and social media presence as a doler of free medical advice. He is also an author, and his Medicine Blue Book, which was first published 1995, is among the best-selling local medical books.Ong also created the Co Tec Tai Medical Museum in Pasay City, the first medical museum in the country." ));

        candidateLists.add(new Model(R.drawable.kiko, "7. PANGILINAN, KIKO" ,"LIBERAL PARTY", "Kiko Pangilinan, 58, is an incumbent senator and the president of the once-ruling Liberal Party.Prior to his marriage to actress Sharon Cuneta in 1996 and his election to the Senate in 2001, he gained fame as a legal commentator in various mass media programs. Pangilinan has served three terms as senator, briefly interrupted by his appointment as food security czar from 2014 to 2015. As chairman of the Senate Agriculture and Food Committee he pushed for the support of the agricultural and fisheries sector, particularly in the 18th Congress. He also currently sits as chairman of the Senate panel on constitutional amendments.", "Food Security, Strengthen Agricultural Sector","R.A. No. 11524, Coconut Farmers and Industry Trust Fund Act, R.A. No. 11511, Amending Republic Act No. 10068 or the Organic Agriculture Act of 2010, R.A. 10929, Free Internet Access in Public Places Act, R.A. No. 11321, or the Sagip Saka Act, R.A. No. 11210, or the 105-Day Expanded Maternity Leave Law" ));

        candidateLists.add(new Model(R.drawable.serapio, "8. SERAPIO, CARLOS","KATIPUNAN NG KAMALAYANG KAYUMANGGI", "Carlos G. Serapio is a lawyer running for vice president under the Katipunan ng Kamalayang Kayumanggi Party. He specializes in cross-border transactions between Japan and the Philippines in his legal practice and served numerous consultancy posts under the Aquino administration’s Office of the President.", "System of Government, Covid 19 Response","Serapio was appointed to several consultancy posts in the Aquino administration.Lead of Consultant Pool Office of the Presidential Adviser on Political Affairs, National Coastwatch Center – Office of the President,Local Government of Catanghalan, Obando, Bulacan" ));

        candidateLists.add(new Model(R.drawable.sotto, "9. SOTTO, VICENTE TITO","NATIONALIST PEOPLE'S COALITION", "Tito Sotto, 73, the incumbent Senate president, has served in Congress for almost two decades and has authored over 100 laws.He has often been tagged as a conservative lawmaker, largely because he continues to block the passage of the SOGIE Equality Bill in the Senate, claiming that some of its provisions trample on religious and academic freedom as well as women’s rights.", "Anti illegal Drug Campaign, Anti-Insurgency, Budget Reform","R.A. 11469 or the Bayanihan to Heal as One Act of 2020,R.A. 11509 or the Doktor Para sa Bayan Act,R.A. 11594 or An Act Increasing the Penalties for Perjury,R.A. 11479 or the Anti-Terrorism Act of 2020,R.A. 11036 or thePhilippine Mental Health Act of 2017" ));



        return candidateLists;
    }


    public static  ArrayList<Model> getSenatorials(){
        ArrayList<Model> candidateLists  = new ArrayList<Model>();
        candidateLists.add(new Model((R.drawable.sen_icon), "1. AFUANG, ABNER ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "2. ALBANI, IBRAHIM ","WORKERS AND PEASANTS PARTY ", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "3. APOLINARIO, PASTOR ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "4. ARCILLA, OSCAR JR. ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "5. ARRANZA, MANG JESS ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "6. BAGUILAT, TEDDY (","LIBERAL PARTY", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "7. BAILEN, AGNES ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "8. BALITA, CARL ","AKSYON DEMOKRATIKO", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "9. BARBO, LUTZ ","PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "10. BAUTISTA, HERBERT BISTEK ","NATIONALIST PEOPLE'S COALITION", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "11. BELGICA, GRECO ","PEDERALISMO NG DUGONG DAKILANG SAMAHAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "12. BELLO, SILVESTRE JR. ","PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "13. BIAZON, DEVIENDO SR. ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "14. BINAY, JOJO ","UNITED NATIONALIST ALLIANCE", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "15. CABONEGRO, ROY ","PARTIDO LAKAS NG MASA", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "16. CASTRICIONES, BRO JOHN ","PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "17. CAYETANO, ALAN PETER ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "18. CHAVEZ, MELCHOR ","WORKERS AND PEASANTS PARTY", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "19. COLMENARES, NERI ","MAKABAYANG KOALISYON NG MAMAMAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "20. D'ANGELO, DAVID ","PARTIDO LAKAS NG MASA", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "21. DE LIMA, LEILA ","LIBERAL PARTY", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "22. DEL ROSARIO, MONSOUR ","PARTIDO PARA SA DEMOKRATIKONG REPORMA", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "23. DIAZ, DING ","PARTIDO PILIPINO SA PAGBABAGO", "", "","" ));


        //51-70
        candidateLists.add(new Model((R.drawable.sen_icon), "51. MATULA, JOSE SONNY ","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "52. MINDALANO-ADAM,MARIETA","KATIPUNAN NG KAMALAYANG KAYUMANGGI", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "53. OLARTE, LEO OBIAS","IBIGKIS PINOY MOVEMENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "54. PADILLA, DRA. MINGUITA","PARTIDO PARA SA DEMOKRATIKONG REPORMA", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "55. PADILLA, ROBIN","PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "56. PANELO, SAL PANALO","PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "57. PIMENTEL, ASTRA ","PARTIDO DEMOKRATIKO PILIPINO LAKAS NG BAYAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "58. PIÑOL, MANNY","NATIONALIST PEOPLE'S COALITION", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "59. RICABLANCA, WILLIE JR."," PARTIDO MAHARLIKA", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "60. ROQUE, HARRY SPOX","PEOPLE'S REFORM PARTY", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "61. SAHIDULLA, LADY ANNE","PEDERALISMO NG DUGONG DAKILANG SAMAHAN", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "62. SISON, JOPET","AKSYON DEMOKRATIKO", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "63. TEODORO, GIBO","PEOPLE'S REFORM PARTY", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "64. TRILLANES, ANTONIO IV","LIBERAL PARTY ", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "65. TULFO, IDOL RAFFY","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "66. VALEROS, REY","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "67. VILLANUEVA, JOEL TESDAMAN","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "68. VILLAR, MARK","INACIONALISTA PARTY", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "69. ZUBIAGA, CARMEN","INDEPENDENT", "", "","" ));
        candidateLists.add(new Model((R.drawable.sen_icon), "70. ZUBIRI, MIGZ ","INDEPENDENT", "", "","" ));

        return candidateLists;
    }
}
